apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  selector:
    matchLabels:
      app: php
  replicas: 1
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: hseevo.azurecr.io/php-fpm:latest
          ports:
            - containerPort: 9000
          env:
            - name: container-app-database_name
            - name: container-app-database_host
            - name: container-app-database_port
            - name: container-app-database_password
---
apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    app: php
spec:
  selector:
    app: php
  type: ClusterIP
  ports:
    - port: 9000
      protocol: TCP
